# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Get Fyne-Cross
      run: go install github.com/fyne-io/fyne-cross@latest

    - name: Pull Latest Windows Image
      run: fyne-cross windows --pull
      
    - name: Build Fyne App
      run: fyne-cross windows -arch=amd64
