# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  APP_VERSION: 0.0

jobs:

  build:
    name: Create Fyne App
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        
    - name: Get Fyne-Cross
      run: go install github.com/fyne-io/fyne-cross@latest
      
    - name: Build Fyne App
      run: fyne-cross windows -arch=amd64

    - name: Read Fyne Version
      uses: SebRollen/toml-action@v1.2.0
      id: read_toml
      with:
        file: 'FyneApp.toml'
        field: 'Details.Version'

    - name: Pass Fyne Version to Release Version
      run: echo "steps.read_toml.outputs.value" >> "${{ env.APP_VERSION }}"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
          tag_name: ${{ env.APP_VERSION }}
          release_name: Release ${{ env.APP_VERSION }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
